### ISSUE TITLE
DIRT-T: Errors 

### ISSUE THREAD

**Issue by Hossein-Askari** [Solacex/pytorch-implementation-of-DIRT-T#1]
Hi,
I have tried several times to run your code, but I could not fix all errors. Actually there are some modules that I  do not know how to have them.  Could you please let me know what is is pretrainedmodels module?

**Comment by Solacex** [comment]
Hello, 
the pretrainedmodels is a python library from https://github.com/Cadene/pretrained-models.pytorch, which is a library collects various pretrained models for pytorch.  hope it helps.
