### ISSUE TITLE
import pretrainedmodels

### ISSUE THREAD

**Issue by PotatoThanh** [Solacex/pytorch-implementation-of-DIRT-T#3]
Hi,

The code can't import pretrainedmodels module.

Thanks!

**Comment by Solacex** [comment]
Hello, the pretrainedmodels is the lib from https://github.com/Cadene/pretrained-models.pytorch, so I suggest you to install this package. Or replace it with other libs to import pretrained models, eg. torch.hub.

**Comment by PotatoThanh** [comment]
Thanks! btw I have one more question: How to create lmdb files? When I run python train.py it doesn't generate these files.

**Comment by Solacex** [comment]
Hello，as this is a very old code ... so I can remind of the detail of lmdb generation. I think you could try the to_lmdb.py or re-implement the dataloader modules.
